-- ============================================================
-- Statewide Executives — fast-follow seed (Political research fix #2,
-- continued): lieutenant governor, attorney general, secretary of
-- state, treasurer. Governors were seeded separately in
-- statewide_executives_seed.sql; this fills the remaining ~200 rows
-- documented there as a deliberate fast-follow.
--
-- Source: Ballotpedia's current officeholder lists, fetched live during
-- this session (not from model memory):
--   https://ballotpedia.org/List_of_current_lieutenant_governors_in_the_United_States
--   https://ballotpedia.org/List_of_current_attorneys_general_in_the_United_States
--   https://ballotpedia.org/List_of_current_secretaries_of_state_in_the_United_States
--   https://ballotpedia.org/List_of_current_treasurers_in_the_United_States
--
-- Coverage notes (real gaps, not scraping bugs — verify against
-- Ballotpedia directly if a row is ever in question):
--   - Lieutenant governor: no such office in Maine, New Hampshire, Oregon,
--     Wyoming (46/50 have the office); Arizona's office exists but is
--     vacant as of this seed — its first election is later in 2026 (45/46
--     currently filled).
--   - Secretary of State: no such office in Alaska, Hawaii, Utah (47/50).
--   - Treasurer: New York and Texas have a Controller/Comptroller instead
--     of a Treasurer (48/50); several states use a different title for
--     the same role (e.g. Florida's CFO, Minnesota's Commissioner of
--     Management and Budget) — the "treasurer" office key still applies,
--     office title differences are cosmetic.
--   - party is left NULL for offices Ballotpedia lists as officially
--     nonpartisan/appointed rather than guessing an affiliation.
--   - term_start is left NULL where Ballotpedia only gave a year, not a
--     full date — an approximate Jan 1 date would be wrong more often
--     than it'd be right for an "authoritative source" table.
--
-- Run once in the Supabase SQL editor, after statewide_executives_seed.sql.
-- ============================================================

INSERT INTO statewide_executives (state, office, name, party, term_start, source_url) VALUES
  ('AK', 'attorney_general', 'Cori Mills', 'Republican', '2026-05-14', 'https://ballotpedia.org/Attorney_General_of_Alaska'),
  ('AL', 'attorney_general', 'Steve Marshall', 'Republican', '2017-02-10', 'https://ballotpedia.org/Attorney_General_of_Alabama'),
  ('AR', 'attorney_general', 'Tim Griffin', 'Republican', '2023-01-10', 'https://ballotpedia.org/Attorney_General_of_Arkansas'),
  ('AZ', 'attorney_general', 'Kris Mayes', 'Democratic', '2023-01-02', 'https://ballotpedia.org/Attorney_General_of_Arizona'),
  ('CA', 'attorney_general', 'Rob Bonta', 'Democratic', '2021-04-23', 'https://ballotpedia.org/Attorney_General_of_California'),
  ('CO', 'attorney_general', 'Phil Weiser', 'Democratic', '2019-01-08', 'https://ballotpedia.org/Attorney_General_of_Colorado'),
  ('CT', 'attorney_general', 'William Tong', 'Democratic', '2019-01-09', 'https://ballotpedia.org/Attorney_General_of_Connecticut'),
  ('DE', 'attorney_general', 'Kathy Jennings', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Attorney_General_of_Delaware'),
  ('FL', 'attorney_general', 'James Uthmeier', 'Republican', '2025-02-18', 'https://ballotpedia.org/Attorney_General_of_Florida'),
  ('GA', 'attorney_general', 'Chris Carr', 'Republican', '2016-11-01', 'https://ballotpedia.org/Attorney_General_of_Georgia'),
  ('HI', 'attorney_general', 'Anne Lopez', NULL, '2022-12-05', 'https://ballotpedia.org/Attorney_General_of_Hawaii'),
  ('IA', 'attorney_general', 'Brenna Bird', 'Republican', '2023-01-02', 'https://ballotpedia.org/Attorney_General_of_Iowa'),
  ('ID', 'attorney_general', 'Raúl Labrador', 'Republican', '2023-01-02', 'https://ballotpedia.org/Attorney_General_of_Idaho'),
  ('IL', 'attorney_general', 'Kwame Raoul', 'Democratic', '2019-01-15', 'https://ballotpedia.org/Attorney_General_of_Illinois'),
  ('IN', 'attorney_general', 'Todd Rokita', 'Republican', '2021-01-11', 'https://ballotpedia.org/Attorney_General_of_Indiana'),
  ('KS', 'attorney_general', 'Kris Kobach', 'Republican', '2023-01-09', 'https://ballotpedia.org/Attorney_General_of_Kansas'),
  ('KY', 'attorney_general', 'Russell Coleman', 'Republican', '2024-01-01', 'https://ballotpedia.org/Attorney_General_of_Kentucky'),
  ('LA', 'attorney_general', 'Liz Murrill', 'Republican', '2024-01-08', 'https://ballotpedia.org/Attorney_General_of_Louisiana'),
  ('MA', 'attorney_general', 'Andrea Campbell', 'Democratic', '2023-01-04', 'https://ballotpedia.org/Attorney_General_of_Massachusetts'),
  ('MD', 'attorney_general', 'Anthony G. Brown', 'Democratic', '2023-01-03', 'https://ballotpedia.org/Attorney_General_of_Maryland'),
  ('ME', 'attorney_general', 'Aaron Frey', 'Democratic', '2019-01-08', 'https://ballotpedia.org/Attorney_General_of_Maine'),
  ('MI', 'attorney_general', 'Dana Nessel', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Attorney_General_of_Michigan'),
  ('MN', 'attorney_general', 'Keith Ellison', 'Democratic', '2019-01-07', 'https://ballotpedia.org/Attorney_General_of_Minnesota'),
  ('MO', 'attorney_general', 'Catherine Hanaway', 'Republican', '2025-09-08', 'https://ballotpedia.org/Attorney_General_of_Missouri'),
  ('MS', 'attorney_general', 'Lynn Fitch', 'Republican', '2020-01-09', 'https://ballotpedia.org/Attorney_General_of_Mississippi'),
  ('MT', 'attorney_general', 'Austin Knudsen', 'Republican', '2021-01-04', 'https://ballotpedia.org/Attorney_General_of_Montana'),
  ('NC', 'attorney_general', 'Jeff Jackson', 'Democratic', '2025-01-01', 'https://ballotpedia.org/Attorney_General_of_North_Carolina'),
  ('ND', 'attorney_general', 'Drew Wrigley', 'Republican', '2022-02-09', 'https://ballotpedia.org/Attorney_General_of_North_Dakota'),
  ('NE', 'attorney_general', 'Mike Hilgers', 'Republican', '2023-01-05', 'https://ballotpedia.org/Attorney_General_of_Nebraska'),
  ('NH', 'attorney_general', 'John Formella', 'Republican', '2021-04-22', 'https://ballotpedia.org/Attorney_General_of_New_Hampshire'),
  ('NJ', 'attorney_general', 'Jennifer Davenport', 'Democratic', '2026-02-24', 'https://ballotpedia.org/Attorney_General_of_New_Jersey'),
  ('NM', 'attorney_general', 'Raul Torrez', 'Democratic', '2023-01-01', 'https://ballotpedia.org/Attorney_General_of_New_Mexico'),
  ('NV', 'attorney_general', 'Aaron Ford', 'Democratic', '2019-01-07', 'https://ballotpedia.org/Attorney_General_of_Nevada'),
  ('NY', 'attorney_general', 'Letitia James', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Attorney_General_of_New_York'),
  ('OH', 'attorney_general', 'Andy Wilson', 'Republican', '2026-06-08', 'https://ballotpedia.org/Attorney_General_of_Ohio'),
  ('OK', 'attorney_general', 'Gentner Drummond', 'Republican', '2023-01-09', 'https://ballotpedia.org/Attorney_General_of_Oklahoma'),
  ('OR', 'attorney_general', 'Dan Rayfield', 'Democratic', '2024-12-31', 'https://ballotpedia.org/Attorney_General_of_Oregon'),
  ('PA', 'attorney_general', 'Dave Sunday', 'Republican', '2025-01-21', 'https://ballotpedia.org/Attorney_General_of_Pennsylvania'),
  ('RI', 'attorney_general', 'Peter Neronha', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Attorney_General_of_Rhode_Island'),
  ('SC', 'attorney_general', 'Alan Wilson', 'Republican', '2011-01-12', 'https://ballotpedia.org/Attorney_General_of_South_Carolina'),
  ('SD', 'attorney_general', 'Marty J. Jackley', 'Republican', '2023-01-02', 'https://ballotpedia.org/Attorney_General_of_South_Dakota'),
  ('TN', 'attorney_general', 'Jonathan Skrmetti', 'Republican', '2022-09-01', 'https://ballotpedia.org/Attorney_General_of_Tennessee'),
  ('TX', 'attorney_general', 'Ken Paxton', 'Republican', '2023-09-18', 'https://ballotpedia.org/Attorney_General_of_Texas'),
  ('UT', 'attorney_general', 'Derek Brown', 'Republican', '2025-01-07', 'https://ballotpedia.org/Attorney_General_of_Utah'),
  ('VA', 'attorney_general', 'Jay Jones', 'Democratic', '2026-01-17', 'https://ballotpedia.org/Attorney_General_of_Virginia'),
  ('VT', 'attorney_general', 'Charity Clark', 'Democratic', '2023-01-05', 'https://ballotpedia.org/Attorney_General_of_Vermont'),
  ('WA', 'attorney_general', 'Nick Brown', 'Democratic', '2025-01-13', 'https://ballotpedia.org/Attorney_General_of_Washington'),
  ('WI', 'attorney_general', 'Josh Kaul', 'Democratic', '2019-01-07', 'https://ballotpedia.org/Attorney_General_of_Wisconsin'),
  ('WV', 'attorney_general', 'John B. McCuskey', 'Republican', '2025-01-13', 'https://ballotpedia.org/Attorney_General_of_West_Virginia'),
  ('WY', 'attorney_general', 'Keith G. Kautz', 'Republican', '2025-07-07', 'https://ballotpedia.org/Attorney_General_of_Wyoming'),
  ('AK', 'lieutenant_governor', 'Nancy Dahlstrom', 'Republican', '2022-12-05', 'https://ballotpedia.org/Lieutenant_Governor_of_Alaska'),
  ('AL', 'lieutenant_governor', 'Will Ainsworth', 'Republican', '2019-01-14', 'https://ballotpedia.org/Lieutenant_Governor_of_Alabama'),
  ('AR', 'lieutenant_governor', 'Leslie Rutledge', 'Republican', '2023-01-10', 'https://ballotpedia.org/Lieutenant_Governor_of_Arkansas'),
  ('CA', 'lieutenant_governor', 'Eleni Kounalakis', 'Democratic', NULL, 'https://ballotpedia.org/Lieutenant_Governor_of_California'),
  ('CO', 'lieutenant_governor', 'Dianne Primavera', 'Democratic', '2019-01-08', 'https://ballotpedia.org/Lieutenant_Governor_of_Colorado'),
  ('CT', 'lieutenant_governor', 'Susan Bysiewicz', 'Democratic', '2019-01-09', 'https://ballotpedia.org/Lieutenant_Governor_of_Connecticut'),
  ('DE', 'lieutenant_governor', 'Kyle Evans Gay', 'Democratic', '2025-01-21', 'https://ballotpedia.org/Lieutenant_Governor_of_Delaware'),
  ('FL', 'lieutenant_governor', 'Jay Collins', 'Republican', '2025-08-12', 'https://ballotpedia.org/Lieutenant_Governor_of_Florida'),
  ('GA', 'lieutenant_governor', 'Burt Jones', 'Republican', '2023-01-09', 'https://ballotpedia.org/Lieutenant_Governor_of_Georgia'),
  ('HI', 'lieutenant_governor', 'Keith Regan', 'Democratic', '2026-04-23', 'https://ballotpedia.org/Lieutenant_Governor_of_Hawaii'),
  ('IA', 'lieutenant_governor', 'Chris Cournoyer', 'Republican', '2024-12-16', 'https://ballotpedia.org/Lieutenant_Governor_of_Iowa'),
  ('ID', 'lieutenant_governor', 'Scott Bedke', 'Republican', '2023-01-02', 'https://ballotpedia.org/Lieutenant_Governor_of_Idaho'),
  ('IL', 'lieutenant_governor', 'Juliana Stratton', 'Democratic', '2019-01-14', 'https://ballotpedia.org/Lieutenant_Governor_of_Illinois'),
  ('IN', 'lieutenant_governor', 'Micah Beckwith', 'Republican', '2025-01-13', 'https://ballotpedia.org/Lieutenant_Governor_of_Indiana'),
  ('KS', 'lieutenant_governor', 'David Toland', 'Democratic', '2021-01-04', 'https://ballotpedia.org/Lieutenant_Governor_of_Kansas'),
  ('KY', 'lieutenant_governor', 'Jacqueline Coleman', 'Democratic', '2019-12-10', 'https://ballotpedia.org/Lieutenant_Governor_of_Kentucky'),
  ('LA', 'lieutenant_governor', 'Billy Nungesser', 'Republican', '2016-01-11', 'https://ballotpedia.org/Lieutenant_Governor_of_Louisiana'),
  ('MA', 'lieutenant_governor', 'Kim Driscoll', 'Democratic', '2023-01-05', 'https://ballotpedia.org/Lieutenant_Governor_of_Massachusetts'),
  ('MD', 'lieutenant_governor', 'Aruna Miller', 'Democratic', '2023-01-18', 'https://ballotpedia.org/Lieutenant_Governor_of_Maryland'),
  ('MI', 'lieutenant_governor', 'Garlin Gilchrist II', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Lieutenant_Governor_of_Michigan'),
  ('MN', 'lieutenant_governor', 'Peggy Flanagan', 'Democratic', '2019-01-07', 'https://ballotpedia.org/Lieutenant_Governor_of_Minnesota'),
  ('MO', 'lieutenant_governor', 'David Wasinger', 'Republican', '2025-01-13', 'https://ballotpedia.org/Lieutenant_Governor_of_Missouri'),
  ('MS', 'lieutenant_governor', 'Delbert Hosemann', 'Republican', '2020-01-09', 'https://ballotpedia.org/Lieutenant_Governor_of_Mississippi'),
  ('MT', 'lieutenant_governor', 'Kristen Juras', 'Republican', '2021-01-04', 'https://ballotpedia.org/Lieutenant_Governor_of_Montana'),
  ('NC', 'lieutenant_governor', 'Rachel Hunt', 'Democratic', '2025-01-01', 'https://ballotpedia.org/Lieutenant_Governor_of_North_Carolina'),
  ('ND', 'lieutenant_governor', 'Michelle Strinden', 'Republican', '2024-12-15', 'https://ballotpedia.org/Lieutenant_Governor_of_North_Dakota'),
  ('NE', 'lieutenant_governor', 'Joe Kelly', 'Republican', '2023-01-05', 'https://ballotpedia.org/Lieutenant_Governor_of_Nebraska'),
  ('NJ', 'lieutenant_governor', 'Dale Caldwell', 'Democratic', '2026-01-20', 'https://ballotpedia.org/Lieutenant_Governor_of_New_Jersey'),
  ('NM', 'lieutenant_governor', 'Howie Morales', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Lieutenant_Governor_of_New_Mexico'),
  ('NV', 'lieutenant_governor', 'Stavros Anthony', 'Republican', '2023-01-02', 'https://ballotpedia.org/Lieutenant_Governor_of_Nevada'),
  ('NY', 'lieutenant_governor', 'Antonio Delgado', 'Democratic', '2022-05-25', 'https://ballotpedia.org/Lieutenant_Governor_of_New_York'),
  ('OH', 'lieutenant_governor', 'Jim Tressel', 'Republican', '2025-02-14', 'https://ballotpedia.org/Lieutenant_Governor_of_Ohio'),
  ('OK', 'lieutenant_governor', 'Matt Pinnell', 'Republican', '2019-01-14', 'https://ballotpedia.org/Lieutenant_Governor_of_Oklahoma'),
  ('PA', 'lieutenant_governor', 'Austin Davis', 'Democratic', '2023-01-17', 'https://ballotpedia.org/Lieutenant_Governor_of_Pennsylvania'),
  ('RI', 'lieutenant_governor', 'Sabina Matos', 'Democratic', '2021-04-14', 'https://ballotpedia.org/Lieutenant_Governor_of_Rhode_Island'),
  ('SC', 'lieutenant_governor', 'Pamela Evette', 'Republican', '2019-01-09', 'https://ballotpedia.org/Lieutenant_Governor_of_South_Carolina'),
  ('SD', 'lieutenant_governor', 'Tony Venhuizen', 'Republican', '2025-01-30', 'https://ballotpedia.org/Lieutenant_Governor_of_South_Dakota'),
  ('TN', 'lieutenant_governor', 'Randy McNally', 'Republican', '2017-01-10', 'https://ballotpedia.org/Lieutenant_Governor_of_Tennessee'),
  ('TX', 'lieutenant_governor', 'Dan Patrick', 'Republican', NULL, 'https://ballotpedia.org/Lieutenant_Governor_of_Texas'),
  ('UT', 'lieutenant_governor', 'Deidre Henderson', 'Republican', '2021-01-04', 'https://ballotpedia.org/Lieutenant_Governor_of_Utah'),
  ('VA', 'lieutenant_governor', 'Ghazala Hashmi', 'Democratic', '2026-01-17', 'https://ballotpedia.org/Lieutenant_Governor_of_Virginia'),
  ('VT', 'lieutenant_governor', 'John Rodgers', 'Republican', '2025-01-09', 'https://ballotpedia.org/Lieutenant_Governor_of_Vermont'),
  ('WA', 'lieutenant_governor', 'Denny Heck', 'Democratic', '2021-01-11', 'https://ballotpedia.org/Lieutenant_Governor_of_Washington'),
  ('WI', 'lieutenant_governor', 'Sara Rodriguez', 'Democratic', '2023-01-02', 'https://ballotpedia.org/Lieutenant_Governor_of_Wisconsin'),
  ('WV', 'lieutenant_governor', 'Randy E. Smith', 'Republican', '2025-01-08', 'https://ballotpedia.org/Lieutenant_Governor_of_West_Virginia'),
  ('AL', 'secretary_of_state', 'Wes Allen', 'Republican', '2023-01-16', 'https://ballotpedia.org/Alabama_Secretary_of_State'),
  ('AR', 'secretary_of_state', 'Cole Jester', 'Republican', '2025-01-01', 'https://ballotpedia.org/Arkansas_Secretary_of_State'),
  ('AZ', 'secretary_of_state', 'Adrian Fontes', 'Democratic', '2023-01-02', 'https://ballotpedia.org/Arizona_Secretary_of_State'),
  ('CA', 'secretary_of_state', 'Shirley Weber', 'Democratic', '2021-01-29', 'https://ballotpedia.org/California_Secretary_of_State'),
  ('CO', 'secretary_of_state', 'Jena Griswold', 'Democratic', '2019-01-08', 'https://ballotpedia.org/Colorado_Secretary_of_State'),
  ('CT', 'secretary_of_state', 'Stephanie Thomas', 'Democratic', '2023-01-04', 'https://ballotpedia.org/Connecticut_Secretary_of_State'),
  ('DE', 'secretary_of_state', 'Charuni Patibanda-Sanchez', 'Democratic', '2025-01-29', 'https://ballotpedia.org/Delaware_Secretary_of_State'),
  ('FL', 'secretary_of_state', 'Cord Byrd', 'Republican', '2023-04-26', 'https://ballotpedia.org/Florida_Secretary_of_State'),
  ('GA', 'secretary_of_state', 'Brad Raffensperger', 'Republican', '2019-01-14', 'https://ballotpedia.org/Georgia_Secretary_of_State'),
  ('IA', 'secretary_of_state', 'Paul Pate', 'Republican', '2015-01-01', 'https://ballotpedia.org/Iowa_Secretary_of_State'),
  ('ID', 'secretary_of_state', 'Phil McGrane', 'Republican', '2023-01-02', 'https://ballotpedia.org/Idaho_Secretary_of_State'),
  ('IL', 'secretary_of_state', 'Alexi Giannoulias', 'Democratic', '2023-01-09', 'https://ballotpedia.org/Illinois_Secretary_of_State'),
  ('IN', 'secretary_of_state', 'Diego Morales', 'Republican', '2023-01-01', 'https://ballotpedia.org/Indiana_Secretary_of_State'),
  ('KS', 'secretary_of_state', 'Scott Schwab', 'Republican', '2019-01-14', 'https://ballotpedia.org/Kansas_Secretary_of_State'),
  ('KY', 'secretary_of_state', 'Michael Adams', 'Republican', '2020-01-06', 'https://ballotpedia.org/Kentucky_Secretary_of_State'),
  ('LA', 'secretary_of_state', 'Nancy Landry', 'Republican', '2024-01-08', 'https://ballotpedia.org/Louisiana_Secretary_of_State'),
  ('MA', 'secretary_of_state', 'William Galvin', 'Democratic', NULL, 'https://ballotpedia.org/Massachusetts_Secretary_of_State'),
  ('MD', 'secretary_of_state', 'Susan Lee', 'Democratic', '2023-02-14', 'https://ballotpedia.org/Maryland_Secretary_of_State'),
  ('ME', 'secretary_of_state', 'Shenna Bellows', 'Democratic', '2021-01-04', 'https://ballotpedia.org/Maine_Secretary_of_State'),
  ('MI', 'secretary_of_state', 'Jocelyn Benson', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Michigan_Secretary_of_State'),
  ('MN', 'secretary_of_state', 'Steve Simon', 'Democratic', '2015-01-05', 'https://ballotpedia.org/Minnesota_Secretary_of_State'),
  ('MO', 'secretary_of_state', 'Denny Hoskins', 'Republican', '2025-01-13', 'https://ballotpedia.org/Missouri_Secretary_of_State'),
  ('MS', 'secretary_of_state', 'Michael D. Watson Jr.', 'Republican', '2020-01-09', 'https://ballotpedia.org/Mississippi_Secretary_of_State'),
  ('MT', 'secretary_of_state', 'Christi Jacobsen', 'Republican', '2021-01-04', 'https://ballotpedia.org/Montana_Secretary_of_State'),
  ('NC', 'secretary_of_state', 'Elaine Marshall', 'Democratic', '1997-01-11', 'https://ballotpedia.org/North_Carolina_Secretary_of_State'),
  ('ND', 'secretary_of_state', 'Michael Howe', 'Republican', '2023-01-01', 'https://ballotpedia.org/North_Dakota_Secretary_of_State'),
  ('NE', 'secretary_of_state', 'Bob Evnen', 'Republican', '2019-01-10', 'https://ballotpedia.org/Nebraska_Secretary_of_State'),
  ('NH', 'secretary_of_state', 'David Scanlan', 'Republican', '2022-01-10', 'https://ballotpedia.org/New_Hampshire_Secretary_of_State'),
  ('NJ', 'secretary_of_state', 'Dale Caldwell', 'Democratic', '2026-01-20', 'https://ballotpedia.org/New_Jersey_Secretary_of_State'),
  ('NM', 'secretary_of_state', 'Maggie Toulouse Oliver', 'Democratic', '2016-12-09', 'https://ballotpedia.org/New_Mexico_Secretary_of_State'),
  ('NV', 'secretary_of_state', 'Cisco Aguilar', 'Democratic', '2023-01-02', 'https://ballotpedia.org/Nevada_Secretary_of_State'),
  ('NY', 'secretary_of_state', 'Walter Mosley', 'Democratic', '2024-05-22', 'https://ballotpedia.org/New_York_Secretary_of_State'),
  ('OH', 'secretary_of_state', 'Frank LaRose', 'Republican', '2019-01-12', 'https://ballotpedia.org/Ohio_Secretary_of_State'),
  ('OK', 'secretary_of_state', 'Benjamin Lepak', 'Republican', '2026-04-28', 'https://ballotpedia.org/Oklahoma_Secretary_of_State'),
  ('OR', 'secretary_of_state', 'Tobias Read', 'Democratic', '2025-01-06', 'https://ballotpedia.org/Oregon_Secretary_of_State'),
  ('PA', 'secretary_of_state', 'Al Schmidt', 'Republican', '2023-06-29', 'https://ballotpedia.org/Pennsylvania_Secretary_of_State'),
  ('RI', 'secretary_of_state', 'Gregg Amore', 'Democratic', '2023-01-03', 'https://ballotpedia.org/Rhode_Island_Secretary_of_State'),
  ('SC', 'secretary_of_state', 'Mark Hammond', 'Republican', NULL, 'https://ballotpedia.org/South_Carolina_Secretary_of_State'),
  ('SD', 'secretary_of_state', 'Monae Johnson', 'Republican', '2022-12-05', 'https://ballotpedia.org/South_Dakota_Secretary_of_State'),
  ('TN', 'secretary_of_state', 'Tre Hargett', 'Republican', '2009-01-15', 'https://ballotpedia.org/Tennessee_Secretary_of_State'),
  ('TX', 'secretary_of_state', 'Jane Nelson', 'Republican', '2023-01-07', 'https://ballotpedia.org/Texas_Secretary_of_State'),
  ('VA', 'secretary_of_state', 'Candi King', 'Democratic', '2026-01-17', 'https://ballotpedia.org/Virginia_Secretary_of_State'),
  ('VT', 'secretary_of_state', 'Sarah Copeland Hanzas', 'Democratic', '2023-01-05', 'https://ballotpedia.org/Vermont_Secretary_of_State'),
  ('WA', 'secretary_of_state', 'Steve Hobbs', 'Democratic', '2021-11-22', 'https://ballotpedia.org/Washington_Secretary_of_State'),
  ('WI', 'secretary_of_state', 'Sarah Godlewski', 'Democratic', '2023-03-17', 'https://ballotpedia.org/Wisconsin_Secretary_of_State'),
  ('WV', 'secretary_of_state', 'Kris Warner', 'Republican', '2025-01-13', 'https://ballotpedia.org/West_Virginia_Secretary_of_State'),
  ('WY', 'secretary_of_state', 'Chuck Gray', 'Republican', '2023-01-02', 'https://ballotpedia.org/Wyoming_Secretary_of_State'),
  ('AK', 'treasurer', 'Janelle Earls', NULL, '2025-08-08', 'https://ballotpedia.org/Alaska_Commissioner_of_the_Department_of_Revenue'),
  ('AL', 'treasurer', 'Young Boozer', 'Republican', '2021-10-01', 'https://ballotpedia.org/Alabama_Treasurer'),
  ('AR', 'treasurer', 'John Thurston', 'Republican', '2025-01-01', 'https://ballotpedia.org/Arkansas_Treasurer'),
  ('AZ', 'treasurer', 'Kimberly Yee', 'Republican', '2019-01-07', 'https://ballotpedia.org/Arizona_Treasurer'),
  ('CA', 'treasurer', 'Fiona Ma', 'Democratic', '2019-01-07', 'https://ballotpedia.org/California_Treasurer'),
  ('CO', 'treasurer', 'Dave Young', 'Democratic', '2019-01-08', 'https://ballotpedia.org/Colorado_Treasurer'),
  ('CT', 'treasurer', 'Erick Russell', 'Democratic', '2023-01-04', 'https://ballotpedia.org/Connecticut_Treasurer'),
  ('DE', 'treasurer', 'Colleen Davis', 'Democratic', '2019-01-01', 'https://ballotpedia.org/Delaware_Treasurer'),
  ('FL', 'treasurer', 'Blaise Ingoglia', 'Republican', '2025-07-21', 'https://ballotpedia.org/Florida_Chief_Financial_Officer'),
  ('GA', 'treasurer', 'Steve McCoy', NULL, '2020-08-05', 'https://ballotpedia.org/Georgia_Treasurer'),
  ('HI', 'treasurer', 'Seth Colby', NULL, '2025-12-08', 'https://ballotpedia.org/Hawaii_Director_of_Finance'),
  ('IA', 'treasurer', 'Roby Smith', 'Republican', '2023-01-01', 'https://ballotpedia.org/Iowa_State_Treasurer'),
  ('ID', 'treasurer', 'Julie Ellsworth', 'Republican', '2019-01-07', 'https://ballotpedia.org/Idaho_Treasurer'),
  ('IL', 'treasurer', 'Mike Frerichs', 'Democratic', '2015-01-12', 'https://ballotpedia.org/Illinois_Treasurer'),
  ('IN', 'treasurer', 'Daniel Elliott', 'Republican', '2023-01-01', 'https://ballotpedia.org/Indiana_Treasurer'),
  ('KS', 'treasurer', 'Steven C. Johnson', 'Republican', '2023-01-09', 'https://ballotpedia.org/Kansas_State_Treasurer'),
  ('KY', 'treasurer', 'Mark Metcalf', 'Republican', '2024-01-01', 'https://ballotpedia.org/Kentucky_State_Treasurer'),
  ('LA', 'treasurer', 'John Fleming', 'Republican', '2024-01-08', 'https://ballotpedia.org/Louisiana_State_Treasurer'),
  ('MA', 'treasurer', 'Deb Goldberg', 'Democratic', '2015-01-21', 'https://ballotpedia.org/Massachusetts_Treasurer'),
  ('MD', 'treasurer', 'Dereck Davis', NULL, '2021-12-17', 'https://ballotpedia.org/Maryland_Treasurer'),
  ('ME', 'treasurer', 'Joseph Perry', NULL, '2025-01-06', 'https://ballotpedia.org/Maine_Treasurer'),
  ('MI', 'treasurer', 'Rachael Eubanks', NULL, NULL, 'https://ballotpedia.org/Michigan_Treasurer'),
  ('MN', 'treasurer', 'Erin Campbell', NULL, '2023-08-15', 'https://ballotpedia.org/Minnesota_Commissioner_of_Management_and_Budget'),
  ('MO', 'treasurer', 'Vivek Malek', 'Republican', '2023-01-17', 'https://ballotpedia.org/Missouri_Treasurer'),
  ('MS', 'treasurer', 'David McRae', 'Republican', '2020-01-09', 'https://ballotpedia.org/Mississippi_Treasurer'),
  ('MT', 'treasurer', 'Brendan Beatty', NULL, '2021-01-04', 'https://ballotpedia.org/Montana_Director_of_the_Department_of_Revenue'),
  ('NC', 'treasurer', 'Brad Briner', 'Republican', '2025-01-01', 'https://ballotpedia.org/North_Carolina_Treasurer'),
  ('ND', 'treasurer', 'Thomas Beadle', 'Republican', '2021-01-01', 'https://ballotpedia.org/North_Dakota_Treasurer'),
  ('NE', 'treasurer', 'Joey Spellerberg', 'Republican', '2025-11-06', 'https://ballotpedia.org/Nebraska_Treasurer'),
  ('NH', 'treasurer', 'Monica Mezzapelle', NULL, '2020-03-25', 'https://ballotpedia.org/New_Hampshire_Treasurer'),
  ('NJ', 'treasurer', 'Aaron Binder', NULL, '2026-02-24', 'https://ballotpedia.org/New_Jersey_Treasurer'),
  ('NM', 'treasurer', 'Laura Montoya', 'Democratic', '2023-01-01', 'https://ballotpedia.org/New_Mexico_Treasurer'),
  ('NV', 'treasurer', 'Zach Conine', 'Democratic', '2019-01-07', 'https://ballotpedia.org/Nevada_State_Treasurer'),
  ('OH', 'treasurer', 'Robert Sprague', 'Republican', '2019-01-14', 'https://ballotpedia.org/Ohio_Treasurer'),
  ('OK', 'treasurer', 'Todd Russ', 'Republican', '2023-01-09', 'https://ballotpedia.org/Oklahoma_Treasurer'),
  ('OR', 'treasurer', 'Elizabeth Steiner Hayward', 'Democratic', '2025-01-06', 'https://ballotpedia.org/Oregon_Treasurer'),
  ('PA', 'treasurer', 'Stacy Garrity', 'Republican', '2021-01-19', 'https://ballotpedia.org/Pennsylvania_Treasurer'),
  ('RI', 'treasurer', 'James Diossa', 'Democratic', '2023-01-03', 'https://ballotpedia.org/Rhode_Island_General_Treasurer'),
  ('SC', 'treasurer', 'Curtis Loftis', 'Republican', NULL, 'https://ballotpedia.org/South_Carolina_Treasurer'),
  ('SD', 'treasurer', 'Josh Haeder', 'Republican', '2019-01-07', 'https://ballotpedia.org/South_Dakota_Treasurer'),
  ('TN', 'treasurer', 'David Lillard, Jr.', NULL, '2009-01-15', 'https://ballotpedia.org/Tennessee_Treasurer'),
  ('UT', 'treasurer', 'Marlo Oaks', 'Republican', '2021-07-20', 'https://ballotpedia.org/Utah_State_Treasurer'),
  ('VA', 'treasurer', 'David Richardson', NULL, '2022-06-02', 'https://ballotpedia.org/Virginia_Treasurer'),
  ('VT', 'treasurer', 'Michael Pieciak', 'Democratic', '2023-01-05', 'https://ballotpedia.org/Vermont_Treasurer'),
  ('WA', 'treasurer', 'Mike Pellicciotti', 'Democratic', '2021-01-11', 'https://ballotpedia.org/Washington_Treasurer'),
  ('WI', 'treasurer', 'John Leiber', 'Republican', '2023-01-02', 'https://ballotpedia.org/Wisconsin_Treasurer'),
  ('WV', 'treasurer', 'Larry Pack', 'Republican', '2025-01-13', 'https://ballotpedia.org/West_Virginia_Treasurer'),
  ('WY', 'treasurer', 'Curt Meier', 'Republican', '2019-01-07', 'https://ballotpedia.org/Wyoming_Treasurer')
ON CONFLICT (state, office) DO UPDATE SET
  name = EXCLUDED.name,
  party = EXCLUDED.party,
  term_start = EXCLUDED.term_start,
  source_url = EXCLUDED.source_url,
  updated_at = now();
